### PR TITLE
Determinate Progress AsyncButton

### PR DESCRIPTION
**Pull request by Dean151**
https://github.com/Dean151/ButtonKit/assets/8696821/913e7068-758a-4656-8f42-1ab75d0a759f

Replace #3

### CODE REVIEW

**Review by zshannon — COMMENTED** [review]
this looks great! have you tested it with a macOS preview? that's the only thing i can't really tell from the PR but i'm using the library only on macOS and the slight differences with UIKit are what led me to put up my PR originally because the spinner size was off

**Comment by Dean151** [comment]
> this looks great! have you tested it with a macOS preview? that's the only thing i can't really tell from the PR but i'm using the library only on macOS and the slight differences with UIKit are what led me to put up my PR originally because the spinner size was off

I've yet to test and build more styles, but I first have to shape the exposed API to be flexible enough for all use case.
With this implementation, it should be possible to mimic the App Store Download button, that transform in a circle, first indeterminate, then determinate.
I'll have to test to build it to make sure it is possible!

**Comment by Dean151** [comment]
Here is the macOS button:
https://github.com/Dean151/ButtonKit/assets/8696821/de9d8239-b84f-4ac6-b51c-f8005f5c62e1

**Comment by zshannon** [comment]
omg take my money how soon can i have this

**Comment by Dean151** [comment]
> omg take my money how soon can i have this

@zshannon I have refactored a bit more, by merging my styles, and making the Progress representation more abstract and flexible for overrides.

It's available as a beta for now, because I might refactor a bit more the way progress is passed in the closure (currently using a Binding, but I'd like to do better if possible)

**Pull request merged**
